/**
 * Turns a config file into the SQL that loads it.
 *
 * Prints, rather than executing. Configuration decides which account
 * gets watched, which pixel belongs to which brand and how much may be
 * spent on the model, so it is worth being able to read the statements
 * before they run. Piping it straight into the database is available to
 * anyone who wants it and is not the default.
 *
 *   node tools/config-sql.ts local-config.json > config.sql
 *   npx wrangler d1 execute meta-ads-agent -c wrangler.local.jsonc \
 *     --remote --file config.sql
 *
 * Re-running it is safe: every statement upserts, so this is also how
 * you change a threshold later.
 */

import { readFileSync } from "node:fs";

/** SQLite quoting: a single quote is escaped by doubling it. */
function q(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function setting(key: string, value: unknown): string {
  return (
    `insert into settings (key, value, updated_at) ` +
    `values (${q(key)}, ${q(JSON.stringify(value))}, datetime('now')) ` +
    `on conflict(key) do update set value = excluded.value, updated_at = excluded.updated_at;`
  );
}

const path = process.argv[2] ?? "local-config.json";
const raw = JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;

const lines: string[] = [
  "-- Generated by tools/config-sql.ts. Safe to run more than once.",
  "",
];

// Anything starting with an underscore is a comment in the JSON file,
// which has no comment syntax of its own. It must not reach the database.
const keys = ["account", "thresholds", "notify", "budget", "retiredPixels", "customerAreas",
  "maxProposalsPerDay", "proposalTtlDays", "enabled"];
for (const key of keys) {
  if (raw[key] === undefined) continue;
  lines.push(setting(key, raw[key]));
}

const brands = Array.isArray(raw.brands) ? raw.brands : [];
if (brands.length > 0) lines.push("");

for (const entry of brands) {
  const brand = entry as Record<string, unknown>;
  const own = brand.thresholds ? q(JSON.stringify(brand.thresholds)) : "null";
  lines.push(
    `insert into brands (id, display_name, campaign_prefix, pixel_id, domain, thresholds) ` +
      `values (${q(String(brand.id))}, ${q(String(brand.displayName))}, ` +
      `${q(String(brand.campaignPrefix))}, ${q(String(brand.pixelId))}, ` +
      `${brand.domain ? q(String(brand.domain)) : "null"}, ${own}) ` +
      `on conflict(id) do update set ` +
      `display_name = excluded.display_name, campaign_prefix = excluded.campaign_prefix, ` +
      `pixel_id = excluded.pixel_id, domain = excluded.domain, thresholds = excluded.thresholds;`,
  );
}

console.log(lines.join("\n"));
